---
- hosts: all
  gather_facts: yes
  become: yes # Run tasks with sudo privileges

  tasks:
    - name: Update apt cache and upgrade all packages
      ansible.builtin.apt:
        update_cache: yes
        #upgrade: dist # Performs a 'dist-upgrade', which handles dependency changes

    - name: Check if a reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_checksum: no
      register: reboot_required_file

    - name: Reboot the server (if required)
      ansible.builtin.reboot:
      when: reboot_required_file.stat.exists == true

    - name: Remove dependencies that are no longer required
      ansible.builtin.apt:
        autoremove: yes