---
- hosts: nodes
  gather_facts: yes
  become: yes # Run tasks with sudo privileges

  tasks:
    - name: Update apt cache and upgrade all packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: yes 

    - name: Remove dependencies that are no longer required
      ansible.builtin.apt:
        autoremove: yes
        #test